version: "3"
services:

  janus:
    image: quay.io/hellofresh/janus
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - api-task
      - api-auth
      - api-public
    volumes:
      - ./janus.toml:/etc/janus/janus.toml
      - ./apis:/etc/janus/apis
      - ./auth:/etc/janus/auth

  api-postgres:
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=test
      - DB_PASS=test
      - DB_NAME=test

  api-task:
    image: img-task-go
    environment:
      - DATASTORE_URL=postgresql://test:test@api-postgres:5432/test?sslmode=disable
      - PORT=3000
    ports:
      - "9089:3000"
    depends_on:
      - api-postgres

  api-auth:
    image: img-auth-go
    ports:
      - "9088:8000"

  api-public:
    image: img-public-go
    ports:
      - "9087:8000"